name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Pull supabase containers in background
        run: |
          pnpm run supabase:start:ci &

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run build
        run: ./scripts/build.sh

      - name: Wait for Supabase to be ready
        run: |
          timeout=180
          counter=0
          until curl -s http://localhost:54321/rest/v1/ >/dev/null; do
            if [ $counter -gt $timeout ]; then
              echo "Timed out waiting for Supabase"
              exit 1
            fi
            echo "Waiting for Supabase to be ready..."
            sleep 1
            counter=$((counter + 1))
          done
          echo "Supabase is ready!"

      - name: Run tests
        run: ./scripts/test.sh

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prod

      - name: Build packages
        run: ./scripts/build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            packages/frontend/dist/
            packages/shared/dist/
          retention-days: 7
